name: Zip, Changelog, and Release Folders

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: read

jobs:
  zip-changelog-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up zip
        run: sudo apt-get install -y zip

      - name: Zip lab1
        run: zip -r lab1.zip lab1

      - name: Zip lab2
        run: zip -r lab2.zip lab2

      - name: Zip microwave
        run: zip -r microwave.zip microwave

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration: changelog-config.json

      - name: Create Release and Upload All Zips
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lab1.zip
            lab2.zip
            microwave.zip
          body: ${{ steps.build_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
